### ISSUE TITLE
Load model

### ISSUE THREAD

**Issue by Yousra-Regaya** [innat/VideoSwin#6]
Hi

I am trying to load model "TFVideoSwinB_SSV2_K400_P244_W1677_32x224.h5" using tensorflow.keras.models.load_model; however, I am getting the following error: ValueError: No model config found in the file at <tensorflow.python.platform.gfile.GFile object at 0x000001F018175B50>. Kindly advise.

**Comment by innat** [comment]
It's because you're trying to load `TF`* prefix checkpoint which created for `keras 2`.  You need to load keras 3 checkpoint. 

For details, please share the reproducible code.

**Comment by innat** [comment]
Clossing it for inactivity.
