### ISSUE TITLE
cannot find or open /content/TFVideoSwinB_SSV2_K400_P244_W1677_32x224.zip

### ISSUE THREAD

**Issue by bitabaroutian** [innat/VideoSwin#7]
Hi,
I'm using the colab notebook linked to this project and while downloading the backbone:
backbone_name = "TFVideoSwinB_SSV2_K400_P244_W1677_32x224"

!wget 'https://github.com/innat/VideoMAE/releases/download/v1.1/{backbone_name}.zip'
!unzip -q '/content/{backbone_name}.zip'

**i get this error:**

--2024-11-11 08:02:17--  https://github.com/innat/VideoMAE/releases/download/v1.1/TFVideoSwinB_SSV2_K400_P244_W1677_32x224.zip
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-11 08:02:17 ERROR 404: Not Found.

unzip:  cannot find or open /content/TFVideoSwinB_SSV2_K400_P244_W1677_32x224.zip, /content/TFVideoSwinB_SSV2_K400_P244_W1677_32x224.zip.zip or /content/TFVideoSwinB_SSV2_K400_P244_W1677_32x224.zip.ZIP.

Thanks

**Comment by innat** [comment]
You can try as follows 

```bash
wget https://github.com/innat/VideoSwin/releases/download/v1.1/TFVideoSwinB_SSV2_K400_P244_W1677_32x224.zip

Length: 335787590 (320M) [application/octet-stream]
Saving to: ‘TFVideoSwinB_SSV2_K400_P244_W1677_32x224.zip’

B_SSV2_K400_P244_W1677_32x22   1%[                                            ]   5.99M  1.10MB/s    eta 4m 30s ^
```
